### ISSUE TITLE
Question regarding the commands and introduction in your README.

### ISSUE THREAD

**Issue by tangg555** [TUDB-Labs/MixLoRA#18]
Hi, I noticed that the configuration details provided in the current README are quite different from those in the [MoE-PEFT](https://github.com/TUDB-Labs/MoE-PEFT) repository. I'm certain I'm using version 1.0.1 as specified in the README.

For example, there's no task named "yahma/alpaca-cleaned," so the command `python launch.py gen --template mixlora --tasks yahma/alpaca-cleaned `doesn't seem to work.

**Comment by mikecovlee** [comment]
Sorry this is a bug. I will fix this soon. Thanks for reporting!
