### ISSUE TITLE
[help] Question about reproduction

### ISSUE THREAD

**Issue by Travis-Tang-chen** [TUDB-Labs/MixLoRA#19]
Hi

I've been able to reproduce the results of LLaMA 3 successfully, but I'm noticing significant discrepancies with other models like Gemma 2 and LLaMA 2 (especially Gemma 2). Do you think this could be an issue with parameter settings, or might there be other factors at play?

**Comment by mikecovlee** [comment]
We encountered similar problems during the iteration of the code. You can try to use `MOE_PEFT_EVALUATE_MODE` to solve this problem. In addition, due to the problems of Google's official code and Config, Gemma's support is not very stable. We have noticed this problem and are constantly trying to fix it.

**Comment by mikecovlee** [comment]
In addition, our experiments are based on version 0.3.1 of https://github.com/mikecovlee/mLoRA. You can try to reproduce the scores in our paper using the original version.

**Comment by Travis-Tang-chen** [comment]
Thank you for your response. I'm currently using version 0.3.1. The results for LLaMA 3 are quite close to the paper's findings, but I'm having some difficulty replicating the results for other models. Even Llama 2 is lower than expected. Could you advise on how to enable MOE_PEFT_EVALUATE_MODE? Thanks! This code is amazing, and I look forward to any future updates.

**Comment by mikecovlee** [comment]
`export MOE_PEFT_EVALUATE_MODE=1` before running MoE-PEFT. This function requires latest version of MoE-PEFT.

**Comment by tangg555** [comment]
Hi, I recently discovered that I'm not using the recommended mlora 0.3.1 version. Instead, based on the MixLoRA project's suggestion, I'm using [MoE-PEFT v1.0.1](https://github.com/TUDB-Labs/MoE-PEFT/tree/1.0.1). I tried switching to 0.3.1, but ran into some issues, e.g., it lacks templates and can't execute launch.py to create a config file.

**Comment by mikecovlee** [comment]
> Hi, I recently discovered that I'm not using the recommended mlora 0.3.1 version. Instead, based on the MixLoRA project's suggestion, I'm using [MoE-PEFT v1.0.1](https://github.com/TUDB-Labs/MoE-PEFT/tree/1.0.1). I tried switching to 0.3.1, but ran into some issues, e.g., it lacks templates and can't execute launch.py to create a config file.

Yes, unfortunately we only support older LLaMA series models (LLaMA 1/2, Mistral) for m-LoRA 0.3.1 version.

**Comment by Travis-Tang-chen** [comment]
Ok. Many thanks for your quick answering. :-)

**Comment by wkzCode** [comment]
> Ok. Many thanks for your quick answering. :-)

I've run into the same problem. Could you tell me how you solved it?
